export {
  useUpload,
  useDogPhotoUpload,
  useActivityMediaUpload,
  useAvatarUpload,
  useBatchUpload,
} from './useUpload';

export {
  useRealtime,
  useRealtimeActivities,
  useRealtimePresence,
  useRealtimeTrainingBoard,
  useRealtimeNotifications,
  useRealtimeBroadcast,
} from './useRealtime';

// Data fetching hooks with React Query
export {
  // Dogs
  useDogs,
  useDog,
  useCreateDog,
  useUpdateDog,
  useDogsWithPrograms,
  // Programs
  usePrograms,
  useActivePrograms,
  useProgram,
  // Families
  useFamilies,
  useFamily,
  useCreateFamily,
  // Training Board / Activities
  useTrainingBoard,
  useStartActivity,
  useEndActivity,
  useQuickLog,
  type TrainingBoardDog,
  // Badges
  useDogBadges,
  useAwardBadge,
  // Analytics
  useDashboardStats,
  // Reports
  useReports,
  useDogsNeedingReports,
  // Pet Parent Portal
  usePetParentFamily,
  usePetParentDogs,
  usePetParentDashboard,
  usePetParentReports,
  usePetParentGallery,
  usePetParentAchievements,
  // Homework System
  useHomeworkTemplates,
  useHomeworkTemplate,
  useCreateHomeworkTemplate,
  useUpdateHomeworkTemplate,
  useDeleteHomeworkTemplate,
  useHomeworkAssignments,
  useHomeworkAssignment,
  useDogHomework,
  useOverdueHomework,
  useCreateHomeworkAssignment,
  useCreateHomeworkFromTemplate,
  useUpdateHomeworkAssignment,
  useCompleteHomeworkAssignment,
  useDeleteHomeworkAssignment,
  useHomeworkSubmissions,
  usePendingHomeworkReviews,
  useCreateHomeworkSubmission,
  useReviewHomeworkSubmission,
  useApproveHomeworkSubmission,
  useHomeworkDashboardStats,
  usePetParentHomework,
  usePetParentHomeworkDetail,
  // Messaging System
  useConversations,
  usePetParentConversations,
  useConversation,
  useCreateConversation,
  useUpdateConversation,
  useUnreadMessageCount,
  usePetParentUnreadCount,
  useMessages,
  useSendMessage,
  useMarkMessagesAsRead,
  useEditMessage,
  useDeleteMessage,
  useAddReaction,
  useRemoveReaction,
  useMessageTemplates,
  useCreateMessageTemplate,
  useUpdateMessageTemplate,
  useDeleteMessageTemplate,
  // Calendar System
  useBoardTrainStays,
  useActiveStays,
  useUpcomingStays,
  useBoardTrainStay,
  useCreateStay,
  useUpdateStay,
  useCheckInStay,
  useCheckOutStay,
  useCancelStay,
  useDeleteStay,
  useCalendarAppointments,
  useUpcomingAppointments,
  useCalendarAppointment,
  useCreateAppointment,
  useUpdateAppointment,
  useConfirmAppointment,
  useCompleteAppointment,
  useCancelAppointment,
  useDeleteAppointment,
  useCalendarBlocks,
  useCreateBlock,
  useUpdateBlock,
  useDeleteBlock,
  useScheduleTemplates,
  useCreateScheduleTemplate,
  useUpdateScheduleTemplate,
  useDeleteScheduleTemplate,
  useStayDailyLogs,
  useStayDailyLog,
  useCreateDailyLog,
  useUpdateDailyLog,
  useUpsertDailyLog,
  useCalendarEvents,
  usePetParentStays,
  usePetParentAppointments,
  // Daily Reports System
  useDailyReports,
  useTodaysReports,
  useDraftReports,
  useReadyReports,
  useDailyReport,
  useDogReport,
  useGenerateReport,
  useUpdateDailyReport,
  useMarkReportReady,
  useSendReport,
  useBulkSendReports,
  useRegenerateSummary,
  useDeleteReport,
  useReportStats,
  useReportTemplates,
  useDefaultReportTemplate,
  useCreateReportTemplate,
  useUpdateReportTemplate,
  useDeleteReportTemplate,
  useReportComments,
  useAddReportComment,
  useUpdateReportComment,
  useDeleteReportComment,
  useReportReactions,
  useAddReportReaction,
  useRemoveReportReaction,
  // Video Library
  useTrainingVideos,
  useTrainingVideo,
  useFeaturedVideos,
  useCreateVideo,
  useUpdateVideo,
  useDeleteVideo,
  useVideoFolders,
  useCreateVideoFolder,
  useVideoPlaylists,
  useVideoPlaylist,
  useShareVideo,
  useVideoLibraryStats,
  // Live Status Feed
  useDogStatusFeed,
  useFacilityStatusFeed,
  useStatusPresets,
  useCreateStatusUpdate,
  useCreateStatusFromPreset,
  useUpdateStatusItem,
  useDeleteStatusItem,
  useAddFeedReaction,
  useRemoveFeedReaction,
  useAddFeedComment,
  useUpdateFeedComment,
  useDeleteFeedComment,
  usePetParentStatusFeed,
  // Business Mode Configuration
  useFacilityConfig,
  useFeatureFlags,
  useUpdateFacilityConfig,
  useSwitchBusinessMode,
  useFeaturePresets,
  useApplyPreset,
  useToggleFeature,
  // Kennel Management
  useKennels,
  useKennel,
  useAvailableKennels,
  useCreateKennel,
  useUpdateKennel,
  useUpdateKennelStatus,
  useDeleteKennel,
  useKennelQRScan,
  useAssignDogToKennel,
  useReleaseDogFromKennel,
  useDogKennelAssignment,
  useKennelHistory,
  useLogKennelActivity,
  useKennelActivityLogs,
  useDogKennelActivityLogs,
  useTodayKennelActivityLogs,
} from './useData';
